### ISSUE TITLE
add support for Vertical Ancillary Data (VANC)

### ISSUE THREAD

**Issue by sfahadshahzad** [ryanmccartney/ffmpeg-docker#1]
Hi,

I hope your are doing well.

It would be great if you can add libklvanc during ffmpeg compile process that is used for parsing/generation of Vertical Ancillary Data (VANC) commonly found in the Serial Digital Interface (SDI) wire protocol.

https://github.com/stoth68000/libklvanc

The library includes a general parser/decoder and an encoder for VANC lines, as well as the ability to both decode and generate protocols commonly found in SDI, including:

SMPTE ST 334 - CEA-708 closed captions in VANC
SMPTE ST 2016 Active Format Descriptor (AFD) and Bar Data
SCTE-104 Ad triggers
SMPTE ST 2038 arbitrary VANC encapsulation
SMPTE ST 12-2 Timecodes
SMPTE RDD 8 Subtitle Distribution packets

Regards,

Fahad

**Comment by ryanmccartney** [comment]
Hi @sfahadshahzad,`libklvanc` has now been added to the FFMPEG compile process and is available within the container
