### ISSUE TITLE
Node process crash/restart loop when UDP output created with undefined address/port

### ISSUE THREAD

**Issue by geoffhouse** [ryanmccartney/ffmpeg-docker#7]
Lots of errors - spamming the logs.
Seems to try, die, then restart and try again. Perhaps should just try once?

**Comment by ryanmccartney** [comment]
This is expected behaviour, the retrying is important for allows the the connection to establish in the case of a network error. However, there should be currently no sanitisation of the inputs passed to the service

**Comment by ryanmccartney** [comment]
The ability to call the service with an undefined address/port is now prevented with the introduction of validation
